package consts

const (
	GLOBAL_TSXVAULT               = "GLOBAL_TSXVAULT"
	GLOBAL_PASSWORD_CONFIG        = "GLOBAL_PASSWORD_CONFIG"
	GLOBAL_EMAIL_CONFIG           = "GLOBAL_EMAIL_CONFIG"
	GLOBAL_EMAIL_CONFIG_SECRET    = "GLOBAL_EMAIL_CONFIG_SECRET"
	GLOBAL_TRASA_SSH_CERT_ENFORCE = "GLOBAL_TRASA_SSH_CERT_ENFORCE"
	GLOBAL_DEVICE_HYGIENE_CHECK   = "GLOBAL_DEVICE_HYGIENE_CHECK"
	GLOBAL_ERROR_REPORT           = "GLOBAL_ERROR_REPORT"
	GLOBAL_DYNAMIC_ACCESS         = "GLOBAL_DYNAMIC_ACCESS"
	GLOBAL_CLOUDPROXY_APIKEY      = "GLOBAL_CLOUDPROXY_APIKEY"
)
