export const iconName = (name) =>
  [
    'angellist',
    'codepen',
    'envelope',
    'etsy',
    'facebook',
    'flickr',
    'foursquare',
    'github-alt',
    'github',
    'gitlab',
    'instagram',
    'linkedin',
    'medium',
    'pinterest',
    'quora',
    'reddit-alien',
    'soundcloud',
    'stack-overflow',
    'steam',
    'stumbleupon',
    'tumblr',
    'twitch',
    'twitter',
    'google',
    'google-plus-official',
    'vimeo',
    'vk',
    'weibo',
    'wordpress',
    'youtube',
  ].includes(name.toLowerCase())
    ? name.toLowerCase()
    : 'lock';
