
export var ServicesMock = [
    {
        ID: '',
        orgID: '',
        secretKey: '',
        name: 'ssh-host',
        hostname: '192.168.0.1',
        type: 'ssh',
        proxyConfig: {routeRule: '', passHostHeader: false,upstreamServer: '', strictTLSValidation: false },
        passthru: false,
        managedAccounts: '',
        remoteAppName: '',
        adhoc: false,
        nativeLog: false,
        rdpProtocol: '',
        publicKey: '',
        externalProviderName: '',
        externalID: '',
        distroName: '',
        distroVersion: '',
        ipDetails: '',
        createdAt: '',
        updatedAt: '',
    },
    {
        ID: '',
        orgID: '',
        secretKey: '',
        name: 'rdp-host',
        hostname: '192.168.0.2',
        type: 'rdp',
        proxyConfig: {routeRule: '', passHostHeader: false,upstreamServer: '', strictTLSValidation: false },
        passthru: false,
        managedAccounts: '',
        remoteAppName: '',
        adhoc: false,
        nativeLog: false,
        rdpProtocol: 'nla',
        publicKey: '',
        externalProviderName: '',
        externalID: '',
        distroName: '',
        distroVersion: '',
        ipDetails: '',
        createdAt: '',
        updatedAt: '',
    },
    {
        ID: '',
        orgID: '',
        secretKey: '',
        name: 'http-host',
        hostname: '192.168.0.3',
        type: 'http',
        proxyConfig: {routeRule: '', passHostHeader: false,upstreamServer: '', strictTLSValidation: false },
        passthru: false,
        managedAccounts: '',
        remoteAppName: '',
        adhoc: false,
        nativeLog: false,
        rdpProtocol: '',
        publicKey: '',
        externalProviderName: '',
        externalID: '',
        distroName: '',
        distroVersion: '',
        ipDetails: '',
        createdAt: '',
        updatedAt: '',
    }
    
    ]