name: Build

on :
  push:
    paths:
      - "app/**"
      - ".github/workflows/build-mobileapp.yaml"

    branches:
      - master
      - ci-update

  pull_request:
    paths:
      - "app/**"
      - ".github/workflows/build-mobileapp.yaml"

    branches:
      - master
jobs:
  build-mobileapp:
    name: Build Dashboard
    runs-on: ubuntu-20.04
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install npm packages
        working-directory: ./mobileapp
        run: yarn install

      - name: Build App
        #TODO treat warning as errors
        env:
          CI: false
        working-directory: ./mobileapp/android
        run: ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: mobileapp/android/app/build/outputs/apk/release/
          retention-days: 1

